DROP TABLE IF EXISTS USER;
CREATE TABLE USER (user_id INT PRIMARY KEY, username VARCHAR(64) NOT NULL, user_first_name VARCHAR(64) NOT NULL, user_last_name VARCHAR(64) NOT NULL, email VARCHAR(64) NOT NULL, password VARCHAR(64) NOT NULL, hours_weekly INT NOT NULL, user_age INT NOT NULL, city VARCHAR(64) NOT NULL, state VARCHAR(64), country VARCHAR(64) NOT NULL);

DROP TABLE IF EXISTS INSTRUMENT;
CREATE TABLE INSTRUMENT (instrument_id INT PRIMARY KEY, instrument_name VARCHAR(64) NOT NULL, isElectronic BOOLEAN NOT NULL, inventor VARCHAR(64), year_created INT);

DROP TABLE IF EXISTS DAW;
CREATE TABLE DAW (daw_id INT PRIMARY KEY, daw_name VARCHAR(64) NOT NULL, runs_on_mac BOOLEAN NOT NULL, runs_on_windows BOOLEAN NOT NULL, runs_on_else BOOLEAN NOT NULL);

DROP TABLE IF EXISTS ARTIST;
CREATE TABLE ARTIST (artist_name VARCHAR(64) PRIMARY KEY NOT NULL, most_popular_track VARCHAR(64) NOT NULL, artist_age INT NOT NULL);

DROP TABLE IF EXISTS FAVORITE_ARTIST;
CREATE TABLE FAVORITE_ARTIST (fav_artist_id INT PRIMARY KEY, fav_artist_name VARCHAR(64) NOT NULL, fav_artist_most_popular_track VARCHAR(64) NOT NULL, fav_artist_age INT NOT NULL);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (genre_name VARCHAR(64) PRIMARY KEY NOT NULL, region_of_origin VARCHAR(64) NOT NULL);

DROP TABLE IF EXISTS USES;
CREATE TABLE USES (username VARCHAR(64), daw_name VARCHAR(64), PRIMARY KEY(username, daw_name));

DROP TABLE IF EXISTS LISTENS;
CREATE TABLE LISTENS (username VARCHAR(64), genre_name VARCHAR(64), PRIMARY KEY (username, genre_name));

DROP TABLE IF EXISTS LOVES;
CREATE TABLE LOVES (username VARCHAR(64), fav_artist_name VARCHAR(64), PRIMARY KEY (username, fav_artist_name));

DROP TABLE IF EXISTS PLAYS;
CREATE TABLE PLAYS (username VARCHAR(64), instrument_name VARCHAR(64), PRIMARY KEY (username, instrument_name));

DROP TABLE IF EXISTS BELONGS;
CREATE TABLE BELONGS (instrument_name VARCHAR(64), genre_name VARCHAR(64), PRIMARY KEY(instrument_name, genre_name));

DROP TABLE IF EXISTS LIKES;
CREATE TABLE LIKES (username VARCHAR(64), artist_name VARCHAR(64), PRIMARY KEY(username, artist_name));

